export const clerkAppearance = {
  variables: {
    colorBackground: "#10131a",
    colorNeutral: "#a1a1aa",
    colorPrimary: "#67e8f9",
    colorText: "#f4f4f5",
    colorInputText: "#f4f4f5",
    colorDanger: "#fda4af",
    colorSuccess: "#86efac",
    borderRadius: "1rem",
  },
  elements: {
    rootBox: "w-full",
    cardBox: "w-full shadow-none",
    card: "bg-[#10131a]/95 shadow-none border border-white/10 rounded-[1.5rem]",
    headerTitle: "text-zinc-50",
    headerSubtitle: "text-zinc-400",
    socialButtonsBlockButton:
      "border border-white/10 bg-white/5 text-zinc-50 hover:bg-white/10 shadow-none",
    socialButtonsBlockButtonText: "text-zinc-50",
    formButtonPrimary: "bg-cyan-300 text-black hover:bg-cyan-200 shadow-none",
    formFieldInput: "bg-black/30 border border-white/10 text-white placeholder:text-zinc-500",
    formFieldLabel: "text-zinc-300",
    footerActionLink: "text-cyan-300 hover:text-cyan-200",
    identityPreviewText: "text-white",
    identityPreviewEditButton: "text-cyan-300 hover:text-cyan-200",
    formResendCodeLink: "text-cyan-300 hover:text-cyan-200",
    alertText: "text-rose-200",
    alert: "border border-rose-500/30 bg-rose-500/10",
    dividerLine: "bg-white/10",
    dividerText: "text-zinc-500",
    formFieldAction: "text-zinc-400 hover:text-white",
    formFieldSuccessText: "text-emerald-300",
    footer: "bg-transparent",
    footerActionText: "text-zinc-400",
    userButtonPopoverCard: "bg-zinc-950 border border-white/10 shadow-2xl",
    userButtonPopoverActionButton: "text-zinc-200 hover:bg-white/10",
    userButtonPopoverActionButtonText: "text-zinc-200",
    userButtonPopoverFooter: "hidden",
  },
} as const;
