export const clerkAppearance = {
  variables: {
    colorBackground: "#ffffff",
    colorNeutral: "#64748b",
    colorPrimary: "#163f87",
    colorText: "#0f172a",
    colorInputText: "#0f172a",
    colorDanger: "#b42318",
    colorSuccess: "#0f9960",
    borderRadius: "1rem",
  },
  elements: {
    rootBox: "w-full",
    cardBox: "w-full shadow-none",
    card: "bg-white shadow-none border border-blue-200 rounded-[1.5rem]",
    headerTitle: "hidden",
    headerSubtitle: "hidden",
    socialButtonsBlockButton:
      "border-2 border-blue-200 bg-white text-slate-900 hover:bg-blue-50 shadow-none",
    socialButtonsBlockButtonText: "text-slate-900",
    formButtonPrimary: "bg-[#163f87] text-white hover:bg-[#12346f] shadow-none",
    formFieldInput: "bg-white border-2 border-blue-200 text-slate-900 placeholder:text-slate-400",
    formFieldLabel: "text-slate-700",
    footerActionLink: "text-[#163f87] hover:text-[#12346f]",
    identityPreviewText: "text-slate-900",
    identityPreviewEditButton: "text-[#163f87] hover:text-[#12346f]",
    formResendCodeLink: "text-[#163f87] hover:text-[#12346f]",
    alertText: "text-rose-800",
    alert: "border border-rose-200 bg-rose-50",
    dividerLine: "bg-blue-100",
    dividerText: "text-slate-500",
    formFieldAction: "text-slate-500 hover:text-slate-900",
    formFieldSuccessText: "text-emerald-700",
    footer: "bg-transparent",
    footerActionText: "text-slate-500",
    userButtonPopoverCard: "bg-white border border-blue-200 shadow-[0_20px_60px_rgba(15,23,42,0.10)]",
    userButtonPopoverActionButton: "text-slate-900 hover:bg-blue-50",
    userButtonPopoverActionButtonText: "text-slate-900",
    userButtonPopoverFooter: "hidden",
  },
} as const;
